name: Deploy to ECS Fargate via AWS Copilot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install AWS Copilot CLI
        run: |
          sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          sudo chmod +x /usr/local/bin/copilot

      - name: Deploy Service using Copilot
        working-directory: ./my-fargate-app
        run: |
          copilot svc deploy --name my-fargate-app --env test
